### PR TITLE
Make homepage URL hyperlink and browse it with default browser

### PR DESCRIPTION
**Pull request by linquize**
The user may click the link to the Homepage of that package.
The default web browser will open that URL.

### CODE REVIEW

**Comment by matejc** [comment]
Could you create a separate file (for example: `helpers.js`) for `openFileWithDefault` helper function (I am sure that in the future there will be more), because `interface.js` is meant for nix->js functions and `data.js` is for mostly database oriented functions. Yes, I know, I have to write more comments :)
Otherwise looks good, thanks, I will merge when ready!

**Comment by linquize** [comment]
With d116f61,
`openFileWithDefault` helper function is moved to the newly created `helper.js`.

**Comment by matejc** [comment]
thanks

**Comment by matejc** [comment]
@linquize there might be a problem, I have strange behavior when clicking on any link, at first it did not work at all, so I installed `pkgs.xdg_utils` (xdg-open script inside nodejs `open` library is using some commands from it), and even then, on every click it opens another browser window, with two tabs, which are hardly related to what the link was, I was able to reproduce the error in command line:

```
cd nixui && make node  # to get node_modules updated
sh ./node_modules/open/vendor/xdg-open "https://google.com"
```
and it behavior is the same to this `require("./helper.js").openFileWithDefault("https://google.com");`

it opens this window (I never saw this page before in my life):

xdg-open

while using `xdg-open` command that comes from Nix, works flawlessly - it opens a new tab in existing firefox window  and it actually opened google.com

**Comment by matejc** [comment]
I am reverting this pull request for now

**Comment by linquize** [comment]
My development environment was NixOS VirtualBox Appliance from master branch, KDE, Konqueror+webkit.
I did not install firefox.

**Pull request merged**
